services:
  demo-app:
    image: automaticbytes/demo-app:latest
    ports:
      - 3100:3100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100"]
      interval: 15s
      timeout: 10s
      retries: 10
  tests:
    build: .
    environment:
      - BASE_URL=http://host.docker.internal:3100
    tty: true
    stdin_open: true
    command: /bin/sh -c "npx wait-on $BASE_URL && npx playwright test" 
