services:
  demo-app:
    image: automaticbytes/demo-app:latest
    platform: linux/amd64
    ports:
      - 3100:3100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100"]
      interval: 15s
      timeout: 10s
      retries: 10
  tests:
    build: .
    depends_on:
      demo-app:
        condition: service_healthy
    environment:
      - BASE_URL=http://demo-app:3100
    entrypoint: ["/bin/sh", "-c", "npx wait-on http://demo-app:3100 && npx playwright test"] 
